"""India CETA (episode 4) through the household stage: the final-goods
duty reductions priced against each household's imputed consumption.

The declared first stage (Section 4 of the paper) allocates GBP 157m of
final-goods duty reductions to categories with published spending
detail: clothing GBP 132m, footwear GBP 13m, food and non-alcoholic
beverages GBP 12m.  The enhanced FRS carries clothing and footwear as
one category, so the two are applied jointly (GBP 145m).  Gains are
computed at 100 per cent pass-through (the declared central dial) and
50 per cent as the labelled variant; each category's aggregate gain is
spread across households in proportion to that household's category
spending, the same first-order convention as every price episode.
Spending denominators are rebased to the ONS FYE2022 base, as in the
other second-stage runs.

Run:  python ceta_second_stage.py --dataset <enhanced_frs.h5>
Emits results/generated_ceta.tex, copied to the paper.
"""

import argparse

import numpy as np

from second_stage_energy import P, weighted, wmean, wquantile, variance_split
from second_stage_energy import RESULTS_DIR, PAPER_DIR

DUTY_CLOTHING_FOOTWEAR_M = 132.0 + 13.0   # GBP m/yr, DBT IA final goods
DUTY_FOOD_M = 12.0


def deciles_of(equiv_income, w):
    order = np.argsort(equiv_income)
    cw = np.cumsum(w[order])
    dec = np.zeros(len(equiv_income), dtype=int)
    dec[order] = np.minimum((cw / cw[-1] * 10).astype(int), 9)
    return dec


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", required=True)
    args = ap.parse_args()

    from policyengine_uk import Microsimulation

    yr = P["sim_year"]
    sim = Microsimulation(dataset=args.dataset)
    w = np.asarray(sim.calculate("household_weight", yr))
    equiv_income = np.asarray(sim.calculate("equiv_hbai_household_net_income", yr))
    clothing = np.asarray(sim.calculate("clothing_and_footwear_consumption", yr,
                                        map_to="household"))
    food = np.asarray(sim.calculate(
        "food_and_non_alcoholic_beverages_consumption", yr, map_to="household"))
    spend_raw = np.asarray(sim.calculate("consumption", yr))
    total_spend = spend_raw * (P["ons_total_spend_yr"] / wmean(spend_raw, w))
    dec = deciles_of(equiv_income, w)

    def gains(pt):
        g = np.zeros_like(clothing)
        for cat, duty_m in ((clothing, DUTY_CLOTHING_FOOTWEAR_M),
                            (food, DUTY_FOOD_M)):
            g = g + cat * (pt * duty_m * 1e6 / weighted(cat, w))
        return g

    g100, g50 = gains(1.0), gains(0.5)

    def dstat(g):
        gbp = [wmean(g[dec == d], w[dec == d]) for d in range(10)]
        pct = [100 * weighted(g[dec == d], w[dec == d])
               / weighted(total_spend[dec == d], w[dec == d]) for d in range(10)]
        return gbp, pct

    gbp100, pct100 = dstat(g100)
    gbp50, _ = dstat(g50)

    ss = g100 / np.maximum(total_spend, 1)
    lo, hi = wquantile(ss, w, 0.01), wquantile(ss, w, 0.99)
    t = (ss >= lo) & (ss <= hi)
    between, within = variance_split(ss[t], w[t], dec[t])

    m = {
        "CetaSsAggM": f"{weighted(g100, w) / 1e6:,.0f}",
        "CetaSsGbpDecOne": f"{gbp100[0]:.2f}",
        "CetaSsGbpDecTen": f"{gbp100[9]:.2f}",
        "CetaSsGbpFiftyDecOne": f"{gbp50[0]:.2f}",
        "CetaSsGbpFiftyDecTen": f"{gbp50[9]:.2f}",
        "CetaSsPctSpendDecOne": f"{pct100[0]:.4f}",
        "CetaSsPctSpendDecTen": f"{pct100[9]:.4f}",
        "CetaSsBetweenPct": f"{between:.1f}",
        "CetaSsWithinPct": f"{within:.1f}",
    }
    with open(RESULTS_DIR / "generated_ceta.tex", "w") as f:
        f.write("% generated by ceta_second_stage.py -- do not edit by hand.\n")
        for k, v in m.items():
            f.write(f"\\newcommand{{\\Ss{k}}}{{{v}}}\n")
    import shutil
    shutil.copy(RESULTS_DIR / "generated_ceta.tex",
                PAPER_DIR / "generated_ceta.tex")
    for k, v in m.items():
        print(k, v)


if __name__ == "__main__":
    main()
