"""Ranking-endogeneity robustness: re-rank deciles on HBAI income net of
the model's three native 2023 support instruments (Energy Price
Guarantee, cost-of-living payments, energy-bills rebate) and recompute
the bottom- and top-decile full-stack cushioning rates.  The netting is
approximate: household equivalised income is scaled by the ratio of
net income excluding the three instruments to net income, a declared
approximation.

Run:  python rank_robustness.py --dataset <enhanced_frs.h5>
Emits results/generated_rank.tex, copied to the paper.
"""

import argparse

import numpy as np

from second_stage_energy import P, weighted, wmean
from second_stage_energy import RESULTS_DIR, PAPER_DIR


def deciles_of(y, w):
    order = np.argsort(y)
    cw = np.cumsum(w[order])
    dec = np.zeros(len(y), dtype=int)
    dec[order] = np.minimum((cw / cw[-1] * 10).astype(int), 9)
    return dec


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dataset", required=True)
    args = ap.parse_args()

    from policyengine_uk import Microsimulation

    yr = P["sim_year"]
    sim = Microsimulation(dataset=args.dataset)

    def hh(name):
        return np.asarray(sim.calculate(name, yr, map_to="household"))

    w = np.asarray(sim.calculate("household_weight", yr))
    equiv = np.asarray(sim.calculate("equiv_hbai_household_net_income", yr))
    net = np.asarray(sim.calculate("household_net_income", yr))
    native = hh("epg_subsidy") + hh("cost_of_living_support_payment") \
        + hh("energy_bills_rebate")
    scale = np.divide(net - native, net, out=np.ones_like(net), where=net > 0)
    equiv_net = equiv * scale

    energy_raw = np.asarray(sim.calculate("domestic_energy_consumption", yr))
    base_cap_fy = (P["cap_apr_2021"] + P["cap_oct_2021"]) / 2.0
    rebase = base_cap_fy / wmean(energy_raw, w)
    energy = energy_raw * rebase
    counter_rise = (P["cap_apr_2022"] + P["cap_oct_2022"]) / 2.0 / base_cap_fy - 1.0
    realised_rise = (P["cap_apr_2022"] + P["epg_level"]) / 2.0 / base_cap_fy - 1.0
    dE = energy * counter_rise
    epg = energy * (counter_rise - realised_rise)
    ebss = np.full_like(energy, P["ebss_per_household"])
    mt = sum(hh(v) for v in ["universal_credit", "pension_credit", "tax_credits",
                             "income_support", "housing_benefit", "jsa_income",
                             "esa_income"])
    col = ((mt > 0) * P["col_means_tested"]
           + (hh("state_pension") > 0) * P["col_pensioner"]
           + ((hh("pip") + hh("dla") + hh("attendance_allowance")) > 0)
           * P["col_disability"])
    disc = epg + ebss + col

    out = {}
    for tag, ranking in (("Base", equiv), ("Net", equiv_net)):
        dec = deciles_of(ranking, w)
        for d, key in ((0, "DOne"), (9, "DTen")):
            m = dec == d
            out[f"Rank{tag}{key}"] = 100 * weighted(disc[m], w[m]) / weighted(dE[m], w[m])

    with open(RESULTS_DIR / "generated_rank.tex", "w") as f:
        f.write("% generated by rank_robustness.py -- do not edit by hand.\n")
        for k, v in out.items():
            f.write(f"\\newcommand{{\\Ss{k}}}{{{v:.1f}}}\n")
    import shutil
    shutil.copy(RESULTS_DIR / "generated_rank.tex", PAPER_DIR / "generated_rank.tex")
    print(out)


if __name__ == "__main__":
    main()
