"""List generated LaTeX macros that no manuscript source references.

Read-only audit. It defines "defined" as a ``\\newcommand`` in
``paper/generated_*.tex`` or ``paper/referee_macros.tex``, and "referenced" as
a use of that control sequence anywhere in ``paper/**/*.tex`` other than its
own definition. ``\\cite``-family and ``\\ref``-family commands are LaTeX
built-ins, not macros this repository defines, so they never appear here.

Output is grouped by the analysis script that emits each file, so a decision
to cut a macro can be traced back to the writer that would have to stop
emitting it.

    python analysis/find_unused_macros.py [--paper paper]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

#: Which analysis script writes each generated file. Read from the file's own
#: "% Generated by ..." header when present; this mapping is the fallback and
#: the cross-check.
WRITERS = {
    "generated_results.tex": "analysis/write_paper_results.py",
    "generated_submission.tex": "analysis/write_submission_results.py",
    "generated_factorial.tex": "analysis/write_factorial_results.py",
    "generated_validation.tex": "analysis/write_validation_macros.py",
    "generated_lfs_benchmarks.tex": "analysis/write_lfs_benchmark_results.py",
    "generated_lfs_selection.tex": "analysis/write_lfs_selection_results.py",
    "generated_trade_benchmarks.tex": "analysis/write_trade_benchmark_results.py",
    "referee_macros.tex": "analysis/write_referee_macros.py",
}

#: \newcommand{\Name}{...} or \newcommand\Name{...}, with the optional
#: \newcommand* spelling and \providecommand/\renewcommand siblings.
DEFINITION = re.compile(
    r"\\(?:new|renew|provide)command\*?\s*\{?\s*\\([A-Za-z]+)\s*\}?"
)

HEADER = re.compile(r"^%\s*Generated by\s+([\w./\\-]+)", re.MULTILINE)


def definition_files(paper: Path) -> list[Path]:
    files = sorted(paper.glob("generated_*.tex"))
    referee = paper / "referee_macros.tex"
    if referee.exists():
        files.append(referee)
    return files


def defined_macros(path: Path) -> dict[str, int]:
    """Macro name -> 1-based line of its definition, in file order."""
    found: dict[str, int] = {}
    for number, line in enumerate(path.read_text().splitlines(), start=1):
        for match in DEFINITION.finditer(line):
            found.setdefault(match.group(1), number)
    return found


def used_macros(paper: Path, definition_paths: set[Path]) -> set[str]:
    """Every control sequence used in paper/**/*.tex outside a definition.

    A definition file may itself USE another macro (one generated value
    interpolated into another), so definition files are scanned too — with
    their own \\newcommand heads stripped first, so defining a macro never
    counts as using it.
    """
    used: set[str] = set()
    for path in sorted(paper.rglob("*.tex")):
        text = path.read_text()
        if path in definition_paths:
            text = DEFINITION.sub(" ", text)
        used.update(re.findall(r"\\([A-Za-z]+)", text))
    return used


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--paper", type=Path, default=ROOT / "paper")
    args = parser.parse_args()
    paper = args.paper

    paths = definition_files(paper)
    used = used_macros(paper, set(paths))

    total_defined = 0
    total_unused = 0
    report: list[str] = []
    for path in paths:
        macros = defined_macros(path)
        total_defined += len(macros)
        header = HEADER.search(path.read_text())
        writer = header.group(1) if header else WRITERS.get(path.name, "unknown")
        unused = {
            name: line for name, line in macros.items() if name not in used
        }
        total_unused += len(unused)
        report.append(
            f"\n{path.relative_to(paper.parent)}  "
            f"(writer: {writer})\n"
            f"  {len(macros)} defined, {len(unused)} unreferenced"
        )
        for name, line in sorted(unused.items(), key=lambda item: item[1]):
            report.append(f"    line {line:>4}  \\{name}")

    print("\n".join(report))
    print(
        f"\nTOTAL: {total_defined} macros defined, {total_unused} unreferenced "
        f"({total_defined - total_unused} used)."
    )


if __name__ == "__main__":
    main()
