"""Write paper/referee_macros.tex from results/referee_fixes.json and the
generated submission rows.

Provides: the main-table row split (OBR three-month rows moved to the
appendix on thin-support grounds), the pension-gross cushioning macros, the
take-up headline macros, and the monthly-versus-annual UC bounding macros.

Usage: uv run python analysis/write_referee_macros.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

RESULTS = Path("results")
PAPER = Path("paper")


def split_submission_rows() -> tuple[str, str]:
    text = (PAPER / "generated_submission.tex").read_text()
    match = re.search(r"\\newcommand{\\SubmissionScenarioRows}{%\n(.*?)\n}", text, re.S)
    if not match:
        raise RuntimeError("SubmissionScenarioRows not found in generated_submission.tex")
    rows = [r for r in match.group(1).splitlines() if r.strip()]
    thin = [r for r in rows if r.startswith("OBR & 3 ")]
    main = [r for r in rows if not r.startswith("OBR & 3 ")]
    return "\n".join(main), "\n".join(thin)


def main() -> None:
    d = json.loads((RESULTS / "referee_fixes.json").read_text())
    pension = d["pension_channel"]
    wc = pension["full_tariff_wage_cut"]
    disp = pension["full_tariff_displacement"]
    contrast = pension["contrast"]
    takeup = d["takeup_headline"]["displacement"]
    uc = d["monthly_uc_bounding"]
    spell3 = uc["spells"]["3m"]

    main_rows, thin_rows = split_submission_rows()

    def pct(x: float, nd: int = 1) -> str:
        return f"{100 * x:.{nd}f}"

    lines = [
        "% Generated by analysis/write_referee_macros.py; do not edit.",
        "\\newcommand{\\SubmissionScenarioRowsMain}{%",
        main_rows,
        "}",
        "\\newcommand{\\SubmissionScenarioRowsThin}{%",
        thin_rows,
        "}",
        # Pension channel (unit 12-month, Bernoulli comparator).
        "\\newcommand{\\PensionSeeds}{25}",
        f"\\newcommand{{\\WageCushionPensionGross}}{{{pct(wc['cushioning_pension_gross']['mean'])}}}",
        f"\\newcommand{{\\PensionDisplacedCushionHBAI}}{{{pct(disp['cushioning_hbai']['mean'])}}}",
        f"\\newcommand{{\\DisplacedCushionPensionGross}}{{{pct(disp['cushioning_pension_gross']['mean'])}}}",
        f"\\newcommand{{\\PensionShareWage}}{{{pct(wc['pension_share_of_gross_loss']['mean'])}}}",
        f"\\newcommand{{\\PensionShareDisplaced}}{{{pct(disp['pension_share_of_gross_loss']['mean'])}}}",
        f"\\newcommand{{\\GapHBAIPension}}{{{contrast['cushioning_gap_hbai_pp']:.1f}}}",
        f"\\newcommand{{\\GapPensionGross}}{{{contrast['cushioning_gap_pension_gross_pp']:.1f}}}",
        # Take-up headline (all conventions agree to <0.1pp).
        f"\\newcommand{{\\TakeupDisplacedCentral}}{{{pct(takeup['0.80']['cushioning_rate']['mean'])}}}",
        # Monthly-versus-annual UC bounding.
        f"\\newcommand{{\\MonthlyUCStandardAllowance}}{{{uc['parameters']['standard_allowance_single_25_plus_month']:.2f}}}",
        f"\\newcommand{{\\MonthlyUCTaxMonthlyThree}}{{{spell3['tax_relief_monthly_correct']:,.0f}}}",
        f"\\newcommand{{\\MonthlyUCTaxAnnualThree}}{{{spell3['tax_relief_annual_equivalent']:,.0f}}}",
        f"\\newcommand{{\\MonthlyUCCushionMonthly}}{{{pct(spell3['cushion_share_monthly_correct'])}}}",
        f"\\newcommand{{\\MonthlyUCCushionAnnual}}{{{pct(spell3['cushion_share_annual_equivalent'])}}}",
        "\\newcommand{\\MonthlyUCCushionGap}{"
        f"{100 * (spell3['cushion_share_monthly_correct'] - spell3['cushion_share_annual_equivalent']):.1f}}}",
    ]
    (PAPER / "referee_macros.tex").write_text("\n".join(lines) + "\n")
    print("[written] paper/referee_macros.tex")


if __name__ == "__main__":
    main()
