"""Generate manuscript macros from the sector-validation and trade-build artifacts.

Closes the last hardcoded-number hole in the external-benchmark prose
(Section~\\ref{sec:results-benchmarks} and the supporting appendix): the
predicted and realised aggregate export falls, the two rank correlations and
the customs-basis/mapped trade totals were previously typed into the
manuscript by hand and had drifted from the artifacts.

Inputs
  results/validation_sectors.json  (analysis/build_measured_shocks.py, `make inputs`)
      always required; every key below must be present or this writer fails.
  results/trade_build_totals.json  (analysis/build_trade_by_sic.py, `make inputs`)
      optional. It can only be produced by a build that has the raw HMRC
      uktradeinfo and ONS ABS inputs, so when it is absent the trade-total
      macros are skipped and a warning names them explicitly. The manuscript
      must not reference a macro that this writer did not emit.

Output: paper/generated_validation.tex
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
VALIDATION = ROOT / "results/validation_sectors.json"
TRADE_TOTALS = ROOT / "results/trade_build_totals.json"
OUTPUT = ROOT / "paper/generated_validation.tex"

# Regenerated by `make inputs` (analysis/build_trade_by_sic.py).
TRADE_TOTAL_TARGET = "make inputs"
TRADE_TOTAL_MACROS = (
    "TradeCustomsTotalMn",
    "TradeMappedTotalMn",
    "TradeCustomsTotalBn",
    "TradeMappedTotalBn",
)


def label(path: Path) -> str:
    """Repository-relative path for error and warning messages."""
    return str(path.relative_to(ROOT) if path.is_relative_to(ROOT) else path)


def require(data: dict, key: str, source: Path) -> float:
    """Fetch a required artifact key or fail loudly."""
    if key not in data:
        raise KeyError(
            f"{label(source)} is missing required key '{key}'. "
            "Regenerate it rather than hand-editing the manuscript."
        )
    value = data[key]
    if not isinstance(value, (int, float)):
        raise TypeError(
            f"{label(source)}['{key}'] is {type(value).__name__}, "
            "expected a number."
        )
    return float(value)


def percent(value: float, places: int = 2) -> str:
    """A proportion as a percentage string, e.g. 0.1257 -> '12.57'."""
    return f"{100 * value:.{places}f}"


def correlation(value: float) -> str:
    """A rank correlation at two decimal places, e.g. 0.0 -> '0.00'."""
    return f"{value:.2f}"


def pounds_million(value_gbp: float) -> str:
    """Pounds to £ million, rounded to the published hundred, comma-grouped."""
    return f"{round(value_gbp / 1e6, -2):,.0f}"


def pounds_billion(value_gbp: float) -> str:
    """Pounds to £ billion at one decimal place."""
    return f"{value_gbp / 1e9:.1f}"


def validation_macros() -> dict[str, str]:
    data = json.loads(VALIDATION.read_text())
    return {
        "PredictedAggregateFall": percent(
            require(data, "aggregate_predicted_fall_full", VALIDATION)
        ),
        "RealisedAggregateFall": percent(
            require(data, "aggregate_realised_fall", VALIDATION)
        ),
        "RankCorrTopTen": correlation(
            require(data, "rank_correlation_top10_full_vs_realised", VALIDATION)
        ),
        "ShockRateCorrAll": correlation(
            require(
                data, "rank_correlation_all_shock_full_vs_measured", VALIDATION
            )
        ),
        "PredictedAggregateFallEPD": percent(
            require(data, "aggregate_predicted_fall_epd", VALIDATION)
        ),
        "RankCorrTopTenEPD": correlation(
            require(data, "rank_correlation_top10_epd_vs_realised", VALIDATION)
        ),
    }


def trade_total_macros() -> dict[str, str]:
    """Trade-build totals, or an empty mapping plus a loud warning."""
    if not TRADE_TOTALS.exists():
        skipped = ", ".join(f"\\{name}" for name in TRADE_TOTAL_MACROS)
        print("!" * 72)
        print(
            f"WARNING: {label(TRADE_TOTALS)} is absent, so these "
            f"macros were NOT written: {skipped}."
        )
        print(
            f"Regenerate it with `{TRADE_TOTAL_TARGET}` "
            "(analysis/build_trade_by_sic.py), which needs the raw HMRC "
            "uktradeinfo and ONS Annual Business Survey inputs."
        )
        print(
            "Until then the manuscript must not reference those macros: "
            "LaTeX would fail on an undefined control sequence."
        )
        print("!" * 72)
        return {}
    data = json.loads(TRADE_TOTALS.read_text())
    customs = require(data, "customs_basis_total_gbp", TRADE_TOTALS)
    mapped = require(data, "mapped_to_divisions_total_gbp", TRADE_TOTALS)
    if mapped > customs:
        raise ValueError(
            f"{label(TRADE_TOTALS)}: mapped total "
            f"({mapped:.0f}) exceeds the customs-basis total ({customs:.0f}); "
            "exclusions can only remove value."
        )
    return {
        "TradeCustomsTotalMn": pounds_million(customs),
        "TradeMappedTotalMn": pounds_million(mapped),
        "TradeCustomsTotalBn": pounds_billion(customs),
        "TradeMappedTotalBn": pounds_billion(mapped),
    }


def main() -> None:
    macros = {**validation_macros(), **trade_total_macros()}
    OUTPUT.write_text(
        "% Generated by analysis/write_validation_macros.py; do not edit.\n"
        + "\n".join(
            f"\\newcommand{{\\{name}}}{{{value}}}"
            for name, value in macros.items()
        )
        + "\n"
    )
    for name, value in macros.items():
        print(f"  \\{name} = {value}")
    print(f"Wrote {OUTPUT} ({len(macros)} macros)")


if __name__ == "__main__":
    main()
